# App Info
spring.application.name=order-service
server.port=8082

# Logging
logging.level.root=INFO
logging.level.mta.eda.consumer=DEBUG

# Kafka Connection
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Kafka Consumer
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual_immediate
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Kafka Admin
spring.kafka.admin.fail-fast=false

# Kafka Topics
kafka.consumer.topic=${KAFKA_TOPIC_NAME:orders}
kafka.dlt.topic.name=${KAFKA_TOPIC_NAME}-dlt

# DLT Producer
kafka.dlt.producer.client-id=${spring.application.name}
kafka.dlt.producer.acks=all
kafka.dlt.producer.idempotence=true
kafka.dlt.producer.retries=2147483647
kafka.dlt.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.dlt.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Send 404s for unknown endpoints through ControllerAdvice
spring.web.resources.add-mappings=false
