# Application Info
spring.application.name=cart-service
server.port=8081

# Logging
logging.level.root=INFO
logging.level.mta.eda.producer=DEBUG
logging.level.org.apache.kafka.clients.admin.AdminMetadataManager=WARN
logging.level.org.apache.kafka.clients=WARN
logging.level.org.apache.kafka.common.network=WARN
logging.level.org.springframework.kafka=WARN

# Kafka Connection
spring.kafka.bootstrap-servers=kafka:29092

# Kafka Admin
spring.kafka.admin.fail-fast=false
spring.kafka.admin.properties.allow.auto.create.topics=false

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=2147483647
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1

# Producer Client
spring.general.producer.client-id=cart-service

# Kafka Topic
kafka.topic.name=orders
kafka.topic.partitions=3
kafka.topic.replication-factor=1

# Actuator Health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Send 404s for unknown endpoints through ControllerAdvice
spring.web.resources.add-mappings=false
